server:
  servlet:
    context-path: /micro_movie
  port: 8081
logging:
  file: my.log
spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
info:
  app:
      name:
        micro_movies
      java:
        source:1.8.0_151
        target:1.8.0_151